<a href="https://colab.research.google.com/github/Bkaroline/EstudoDeCaso/blob/main/Case.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [22]:
import pandas as pd

# --- INGESTÃO E LEITURA
dados_entrega = "/content/entregas_orquideas.csv"
dados_qualidade = "/content/estufas_qualidade.csv"
dados_telemetria = "/content/telemetria_iot.csv"

df_dados_entrega = pd.read_csv(dados_entrega)
df_dados_qualidade = pd.read_csv(dados_qualidade)
df_dados_telemetria = pd.read_csv(dados_telemetria)

display(df_dados_entrega.head())
print("\n\n")
display(df_dados_qualidade.head())
print("\n\n")
display(df_dados_telemetria.head())
print("\n\n")

# --- CLASSIFICAÇÃO TEMPERATURA

status_temperatura = []

Temp = df_dados_telemetria["Temperatura_C"].tolist()
for i in Temp:
  if i >= 28:
    status_temperatura.append("ALERTA")
  else:
    status_temperatura.append("OK")


# --- ANALISES DE ESTATISTICA E DIAGNOSTICO

df_dados_telemetria["Classificacao_Temp"] = status_temperatura
display(df_dados_telemetria.head())
print("\n\n")

print(f"O total de Orquideas transportadas foram: {df_dados_entrega["Qtd_Orquideas"].sum()}")
print("\n\n")

df_preju = df_dados_entrega[df_dados_entrega["Status_Entrega"]== "Cancelado"]
print(f"A Quantidade de Orquideas canceladas foram: {df_preju["Status_Entrega"].count()}")
print("\n\n")

df_est = df_dados_entrega[df_dados_entrega["Status_Entrega"]== "Cancelado"]
print(f"O estado que mais apareceu foi: {df_est["UF_Destino"].max()}")
print("\n\n")

print(f"A Temperatura máxima foi:  {df_dados_telemetria["Temperatura_C"].max()}°C e a temperatura média foi: {df_dados_telemetria["Temperatura_C"].mean()}°C")
print("\n\n")

,ID_Carga,Placa_Caminhao,Estufa_Origem,UF_Destino,Qtd_Orquideas,Status_Entrega
0,LOG-1000,TX-103,EST-3,SP,457,Entregue
1,LOG-1001,TX-100,EST-1,SC,165,Entregue
2,LOG-1002,TX-108,EST-2,MG,124,Entregue
3,LOG-1003,TX-107,EST-1,RJ,162,Entregue
4,LOG-1004,TX-107,EST-2,SP,469,Entregue

,id_estufa,especie_predominante,umidade_media_pct,responsavel_tecnico,indice_qualidade_lote
0,EST-1,Phalaenopsis,75,Ana Silva,0.95
1,EST-2,Cattleya,82,Carlos Mendes,0.88
2,EST-3,Dendrobium,65,Mariana Costa,0.91

  Placa_Caminhao  Temperatura_C Alerta_Calor
0         TX-103             20          NAO
1         TX-100             30          SIM
2         TX-108             28          SIM
3         TX-107             33          SIM
4         TX-104             20          NAO

  Placa_Caminhao  Temperatura_C Alerta_Calor Classificacao_Temp
0         TX-103             20          NAO                 OK
1         TX-100             30          SIM             ALERTA
2         TX-108             28          SIM             ALERTA
3         TX-107             33          SIM             ALERTA
4         TX-104             20          NAO                 OK

O total de Orquideas transportadas foram: 55425



A Quantidade de Orquideas canceladas foram: 27



O estado que mais apareceu foi: SP



A Temperatura máxima foi:  34°C e a temperatura média foi: 27.0°C